@host = http://localhost:5035

### Hent kaffemeny
GET {{host}}/menu
Accept: application/json

### Legg inn bestilling
POST {{host}}/orders
Accept: application/json
Content-Type: application/json

{
    "coffeeId": "c3d12ef1-e8cb-4162-993d-7172240a8e4d",
    "size": "Medium",
    "milkType": "Whole",
    "extraShot": true,
    "customerName": "John Doe",
    "quantity": 12
}

### Se den genererte OpenAPI-spesifikasjonen (åpne i browser)
# {{host}}/openapi/v1.json

### Åpne Scalar UI (åpne i browser)
# {{host}}/scalar/v1
